/**
 * Car Database
 * 
 * Complete list of car makes, models, years, types, and fuel types
 * for user vehicle selection during onboarding.
 */

export interface CarData {
  make: string;
  model: string;
  year: number;
  type: string;
  fuelType: string;
}

export const CAR_DATABASE: CarData[] = [
  { make: "Dodge", model: "Ram 1500", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "Infiniti", model: "Q50", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Acura", model: "MDX", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Acura", model: "MDX", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Acura", model: "MDX", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Acura", model: "MDX", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Acura", model: "MDX", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Acura", model: "MDX", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Acura", model: "MDX", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Audi", model: "A4", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2007, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "3 Series", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "5 Series", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "BMW", model: "X5", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "BMW", model: "X5", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "BMW", model: "X5", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "BMW", model: "X5", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "BMW", model: "X5", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Buick", model: "Enclave", year: 2012, type: "SUV", fuelType: "Gasoline" },
  { make: "Buick", model: "Enclave", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Buick", model: "Enclave", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Cadillac", model: "CTS", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Cadillac", model: "CTS", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2016, type: "Hatchback", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado", year: 2018, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado 1500", year: 2015, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado 1500", year: 2017, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado 1500", year: 2018, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado 1500", year: 2020, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Tahoe", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Tahoe", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Bolt EV", year: 2017, type: "Hatchback", fuelType: "Electric" },
  { make: "Chevrolet", model: "Colorado", year: 2016, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Cruze", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Equinox", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Equinox", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Equinox", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Malibu", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Malibu", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Malibu", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Malibu", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado", year: 2015, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado", year: 2018, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado", year: 2020, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chevrolet", model: "Silverado", year: 2021, type: "Pickup", fuelType: "Gasoline" },
  { make: "Chrysler", model: "Pacifica", year: 2019, type: "Minivan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Challenger", year: 2016, type: "Coupe", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Charger", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Durango", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Dodge", model: "Grand Caravan", year: 2013, type: "Minivan", fuelType: "Gasoline" },
  { make: "Dodge", model: "Ram 1500", year: 2016, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "Camry", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Edge", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Escape", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Escape", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Escape", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Escape", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Escape", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Escape", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Escape", year: 2021, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Explorer", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Explorer", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Explorer", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "Explorer", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2004, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2008, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2010, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2015, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2018, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2020, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2021, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "F-150", year: 2022, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ford", model: "Focus", year: 2018, type: "Hatchback", fuelType: "Gasoline" },
  { make: "Ford", model: "Fusion", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Fusion", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Fusion", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Fusion", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Fusion", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Fusion", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Fusion", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Taurus", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Taurus", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Taurus", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Taurus", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Ford", model: "Taurus", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra", year: 2017, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Canyon", year: 2017, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Canyon", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra", year: 2013, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra", year: 2014, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra", year: 2015, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra", year: 2018, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra 1500", year: 2013, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra 1500", year: 2014, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra 1500", year: 2015, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra 1500", year: 2016, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra 1500", year: 2017, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra 1500", year: 2018, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Sierra 1500", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "GMC", model: "Terrain", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "GMC", model: "Terrain", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "GMC", model: "Terrain", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "GMC", model: "Terrain", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "GMC", model: "Terrain", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "GMC", model: "Terrain", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "GMC", model: "Terrain", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Genesis", model: "G80", year: 2020, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Accord", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Accord", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Accord", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Accord", year: 2020, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2021, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "CR-V", year: 2022, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2008, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2020, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Civic", year: 2021, type: "Sedan", fuelType: "Gasoline" },
  { make: "Honda", model: "Pilot", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Honda", model: "Pilot", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Elantra", year: 2020, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Genesis", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Palisade", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Santa Fe", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Santa Fe", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Santa Fe", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Santa Fe", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Hyundai", model: "Tucson", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Infiniti", model: "Q50", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Infiniti", model: "Q50", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2012, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Grand Cherokee", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Wrangler", year: 2012, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Wrangler", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Wrangler", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Wrangler", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Wrangler", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Wrangler", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Jeep", model: "Wrangler", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "K5", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "K5", year: 2021, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Optima", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Optima", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Optima", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Optima", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Optima", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Optima", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Optima", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Kia", model: "Palisade", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sorento", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sorento", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sorento", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sorento", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sorento", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sorento", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sorento", year: 2021, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Soul", year: 2018, type: "Hatchback", fuelType: "Gasoline" },
  { make: "Kia", model: "Sportage", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sportage", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sportage", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Sportage", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Telluride", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Kia", model: "Telluride", year: 2021, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "ES", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Lexus", model: "IS", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2019, type: "SUV", fuelType: "Hybrid" },
  { make: "Lexus", model: "RX", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX", year: 2022, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Lexus", model: "RX 350", year: 2021, type: "SUV", fuelType: "Hybrid" },
  { make: "Mazda", model: "CX-5", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Mazda", model: "CX-5", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Mazda", model: "CX-5", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Mazda", model: "CX-5", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Mazda", model: "CX-5", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Mazda", model: "CX-5", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Mazda", model: "CX-5", year: 2021, type: "SUV", fuelType: "Gasoline" },
  { make: "Mazda", model: "MX-5 Miata", year: 2010, type: "Coupe", fuelType: "Gasoline" },
  { make: "Mazda", model: "MX-5 Miata", year: 2016, type: "Convertible", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda3", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda3", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda3", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda3", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda3", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda3", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda3", year: 2021, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mazda", model: "Mazda6", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "C-Class", year: 2020, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "E-Class", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "E-Class", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "E-Class", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Mercedes-Benz", model: "GLA", year: 2021, type: "SUV", fuelType: "Gasoline" },
  { make: "Mercury", model: "Mariner", year: 2008, type: "SUV", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2008, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Altima", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Maxima", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Rogue", year: 2017, type: "SUV", fuelType: "Gasoline" },
  { make: "Nissan", model: "Rogue", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Nissan", model: "Rogue", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Nissan", model: "Sentra", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Sentra", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Nissan", model: "Versa", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Porsche", model: "Cayenne", year: 2012, type: "SUV", fuelType: "Gasoline" },
  { make: "Porsche", model: "Cayenne", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Porsche", model: "Cayenne", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Ram", model: "1500", year: 2015, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ram", model: "1500", year: 2016, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ram", model: "1500", year: 2017, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ram", model: "1500", year: 2018, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ram", model: "1500", year: 2019, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ram", model: "1500", year: 2020, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ram", model: "1500", year: 2021, type: "Pickup", fuelType: "Gasoline" },
  { make: "Ram", model: "2500", year: 2016, type: "Pickup", fuelType: "Diesel" },
  { make: "Subaru", model: "Outback", year: 2010, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2011, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2012, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2013, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2014, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2015, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2016, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2017, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2018, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2019, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2020, type: "Wagon", fuelType: "Gasoline" },
  { make: "Subaru", model: "Outback", year: 2021, type: "Wagon", fuelType: "Gasoline" },
  { make: "Tesla", model: "Model 3", year: 2017, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model 3", year: 2018, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model 3", year: 2019, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model 3", year: 2020, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model 3", year: 2021, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model 3", year: 2022, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model 3", year: 2023, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model 3", year: 2024, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2012, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2013, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2014, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2015, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2016, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2017, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2018, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2019, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2020, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model S", year: 2021, type: "Sedan", fuelType: "Electric" },
  { make: "Tesla", model: "Model X", year: 2015, type: "SUV", fuelType: "Electric" },
  { make: "Tesla", model: "Model X", year: 2016, type: "SUV", fuelType: "Electric" },
  { make: "Tesla", model: "Model Y", year: 2020, type: "SUV", fuelType: "Electric" },
  { make: "Tesla", model: "Model Y", year: 2021, type: "SUV", fuelType: "Electric" },
  { make: "Tesla", model: "Model Y", year: 2022, type: "SUV", fuelType: "Electric" },
  { make: "Tesla", model: "Model Y", year: 2023, type: "SUV", fuelType: "Electric" },
  { make: "Tesla", model: "Model Y", year: 2024, type: "SUV", fuelType: "Electric" },
  { make: "Toyota", model: "Prius", year: 2010, type: "Hatchback", fuelType: "Hybrid" },
  { make: "Toyota", model: "4Runner", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2018, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2019, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2020, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Camry", year: 2022, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Corolla", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Corolla", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Corolla", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Toyota", model: "Highlander", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "Prius", year: 2009, type: "Hatchback", fuelType: "Hybrid" },
  { make: "Toyota", model: "Prius", year: 2012, type: "Hatchback", fuelType: "Hybrid" },
  { make: "Toyota", model: "Prius", year: 2014, type: "Hatchback", fuelType: "Hybrid" },
  { make: "Toyota", model: "RAV4", year: 2010, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2012, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2013, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2014, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2015, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2017, type: "SUV", fuelType: "Hybrid" },
  { make: "Toyota", model: "RAV4", year: 2018, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2020, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2021, type: "SUV", fuelType: "Gasoline" },
  { make: "Toyota", model: "RAV4", year: 2022, type: "SUV", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Golf", year: 2010, type: "Hatchback", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Golf", year: 2015, type: "Hatchback", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Golf GTI", year: 2013, type: "Hatchback", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Golf GTI", year: 2014, type: "Hatchback", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Jetta", year: 2009, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Jetta", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Jetta", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Jetta", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Jetta", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Jetta", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2010, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2011, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2012, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2013, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2014, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2015, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2016, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volkswagen", model: "Passat", year: 2017, type: "Sedan", fuelType: "Gasoline" },
  { make: "Volvo", model: "XC60", year: 2012, type: "SUV", fuelType: "Diesel" },
  { make: "Volvo", model: "XC60", year: 2016, type: "SUV", fuelType: "Gasoline" },
  { make: "Volvo", model: "XC60", year: 2019, type: "SUV", fuelType: "Gasoline" },
  { make: "Volvo", model: "XC90", year: 2016, type: "SUV", fuelType: "Hybrid" },
  { make: "Volvo", model: "XC90", year: 2018, type: "SUV", fuelType: "Gasoline" },
];

// Helper functions to extract unique values
export const getUniqueMakes = (): string[] => {
  return Array.from(new Set(CAR_DATABASE.map((car) => car.make))).sort();
};

export const getModelsForMake = (make: string): string[] => {
  return Array.from(new Set(CAR_DATABASE.filter((car) => car.make === make).map((car) => car.model))).sort();
};

export const getYearsForMakeModel = (make: string, model: string): number[] => {
  return Array.from(
    new Set(CAR_DATABASE.filter((car) => car.make === make && car.model === model).map((car) => car.year))
  ).sort((a, b) => b - a); // Sort years descending
};

export const getCarDetails = (make: string, model: string, year: number): CarData | undefined => {
  return CAR_DATABASE.find((car) => car.make === make && car.model === model && car.year === year);
};

export const getVehicleTypes = (): string[] => {
  return Array.from(new Set(CAR_DATABASE.map((car) => car.type))).sort();
};

export const getFuelTypes = (): string[] => {
  return Array.from(new Set(CAR_DATABASE.map((car) => car.fuelType))).sort();
};

